apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: jigaree
build:
  artifacts:
  - image: us-central1-docker.pkg.dev/play-with-anthos-340801/jigaree/air
    context: src/air
    ko:
      labels:
        org.opencontainers.image.licenses: Apache-2.0
        org.opencontainers.image.revision: "{{.GITHUB_SHA}}"
        org.opencontainers.image.source: "{{.GITHUB_SERVER_URL}}/{{.GITHUB_REPOSITORY}}"
    platforms:
      - linux/amd64
      - linux/arm64

deploy:
  kubectl:
    manifests:
    - k8s-manifests/redis/deployment.yaml
    - k8s-manifests/redis/svc.yaml

profiles:
- name: dev
  activation:
    - env: AQI_SERVER_URL="https://api.waqi.info"
    - env: AQI_SERVER_TOKEN="b0e78ca32d058a9170b6907c5214c0e946534cc9"
    - env: IP_STACK_SERVER_URL="http://api.ipstack.com"
    - env: IP_STACK_SERVER_TOKEN="ad7c6834f8dba51e8943d96d3742fcc5"