---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - webapp.cc4i.xyz
  resources:
  - jigarees
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapp.cc4i.xyz
  resources:
  - jigarees/finalizers
  verbs:
  - update
- apiGroups:
  - webapp.cc4i.xyz
  resources:
  - jigarees/status
  verbs:
  - get
  - patch
  - update
